ALTER TABLE subscription_plans
    ADD COLUMN IF NOT EXISTS max_teachers INTEGER,
    ADD COLUMN IF NOT EXISTS is_featured  BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS sort_order   INTEGER NOT NULL DEFAULT 0;
