FROM --platform=$BUILDPLATFORM golang:1.23-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -ldflags="-w -s" -o grpc-server ./cmd/grpc/main.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/grpc-server .

EXPOSE 9090

CMD ["./grpc-server"]
