FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags="-w -s" -o grpc-server ./cmd/grpc/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/grpc-server .

EXPOSE 9090

CMD ["./grpc-server"]
